apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
    tier: frontend
  name: wp-svc-clusterip
  namespace: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
  clusterIP: None